# マウス操作を有効にする
set-option -g mouse on

# windowのインデックスを1から始める
set -g base-index 1
setw -g pane-base-index 1
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -g default-terminal "xterm-256color"

# window-statusの見た目を変更
setw -g window-status-current-format '#[bg=colour2,fg=colour255] #I #W '
setw -g window-status-format '#[fg=colour242] #I #W '

setw -g window-status-current-format '#[bg=colour2,fg=colour255]#{?client_prefix,#[bg=colour3],} #I #W '

bind -n M-left previous-window
bind -n M-right next-window

bind -n C-t new-window -a -c "#{pane_current_path}"

bind -n M-\\ split-window -h -c "#{pane_current_path}"
bind -n M-- split-window -v -c "#{pane_current_path}"

bind -n C-w kill-pane

bind -n M-left \
  if-shell -F '#{==:#{pane_index},1}' \
  'previous-window; run "tmux select-pane -t $(tmux list-panes | wc -l)"' \
  'select-pane -t :.-'
bind -n M-right \
  if-shell -F '#{==:#{pane_index},#{window_panes}}' \
  'next-window; select-pane -t 1' \
  'select-pane -t :.+'

# off mode
bind -T root F12 \
  set prefix None\; \
  set key-table off\; \
  set status-style "fg=$color_sub"\; \
  setw -g window-status-style "bg=$color_inactive"\; \
  setw window-status-current-style "bg=$color_sub"\; \
  refresh-client -S
bind -T off F12 \
  set -u prefix\; \
  set -u key-table\; \
  set -u status-style\; \
  setw -g window-status-style "bg=$color_sub"\; \
  setw -u window-status-current-style\; \
  refresh-client -S
